import { useState, type ReactNode } from 'react';
import { Button } from '@/ui/components/Button';
import { FieldLabel } from '@/ui/components/FieldLabel';
import { SelectField } from '@/ui/components/SelectField';
import { TextArea } from '@/ui/components/TextArea';
import { TextField } from '@/ui/components/TextField';
import { FzIcon } from '@/ui/icons';
import type { AvailableEpkTrack, EpkContact, EpkContactRole, EpkDocument, EpkDocumentType, EpkLink, EpkPhoto, EpkRecord, EpkTrack, EpkVideo, EpkVideoType } from './epk';
import { DEFAULT_EPK_SECTION_ORDER, type EpkSectionId } from './epkPresentation';

const labels: Record<EpkSectionId, string> = { banniere: 'Bannière', bio: 'Biographie', musique: 'Musique', medias: 'Médias', espacePro: 'Espace Pro', contact: 'Contact' };
const accentSwatches = [['#ff3a63', 'Rose FaderZero', 'bg-[#ff3a63]'], ['#f97316', 'Orange', 'bg-orange-500'], ['#facc15', 'Jaune', 'bg-yellow-400'], ['#4ade80', 'Vert', 'bg-green-400'], ['#2dd4bf', 'Turquoise', 'bg-teal-400'], ['#38bdf8', 'Bleu ciel', 'bg-sky-400'], ['#818cf8', 'Indigo', 'bg-indigo-400'], ['#c084fc', 'Violet', 'bg-purple-400']] as const;
const platforms = ['Spotify', 'Apple Music', 'YouTube Music', 'Deezer', 'SoundCloud', 'Bandcamp', 'Amazon Music', 'Tidal', 'Qobuz'];
const socials = ['Instagram', 'Facebook', 'YouTube', 'X', 'TikTok', 'LinkedIn', 'Twitch'];

type Props = {
  epk: EpkRecord; onChange: (next: EpkRecord) => void; onSave: () => void; saving: boolean;
  tracks: EpkTrack[]; availableTracks: AvailableEpkTrack[]; videos: EpkVideo[]; photos: EpkPhoto[]; documents: EpkDocument[]; contacts: EpkContact[]; links: EpkLink[];
  onAddTrack: (id: string) => void; onRemoveTrack: (item: EpkTrack) => void; onAddVideo: (url: string, title: string, type: EpkVideoType) => void; onRemoveVideo: (item: EpkVideo) => void;
  onUploadHero: (file: File) => void; onUploadPhoto: (file: File) => void; onRemovePhoto: (item: EpkPhoto) => void; onUploadDocument: (file: File, title: string, type: EpkDocumentType) => void; onRemoveDocument: (item: EpkDocument) => void;
  onAddContact: (name: string, role: EpkContactRole, value: string, type: 'email' | 'phone') => void; onRemoveContact: (item: EpkContact) => void; onAddLink: (name: string, url: string) => void; onRemoveLink: (item: EpkLink) => void;
};

export function EpkEditorFields(props: Props) {
  const { epk, onChange, saving } = props;
  const [trackId, setTrackId] = useState(''); const [videoUrl, setVideoUrl] = useState(''); const [videoTitle, setVideoTitle] = useState(''); const [documentTitle, setDocumentTitle] = useState(''); const [documentType, setDocumentType] = useState<EpkDocumentType>('TECH_RIDER'); const [contactName, setContactName] = useState(''); const [contactRole, setContactRole] = useState<EpkContactRole>('BOOKING'); const [contactValue, setContactValue] = useState(''); const [contactType, setContactType] = useState<'email' | 'phone'>('email'); const [platform, setPlatform] = useState(platforms[0] ?? 'Spotify'); const [platformUrl, setPlatformUrl] = useState(''); const [social, setSocial] = useState(socials[0] ?? 'Instagram'); const [socialUrl, setSocialUrl] = useState('');
  const updateSections = (sectionOrder: EpkSectionId[], hiddenSections = epk.hiddenSections ?? []) => onChange({ ...epk, sectionOrder, hiddenSections });
  const move = (index: number, direction: -1 | 1) => { const next = [...(epk.sectionOrder ?? DEFAULT_EPK_SECTION_ORDER)]; const target = index + direction; if (index === 0 || target < 1 || target >= next.length) return; [next[index], next[target]] = [next[target]!, next[index]!]; updateSections(next); };
  const updateFacts = (facts: EpkRecord['editorial']['facts']) => onChange({ ...epk, editorial: { ...epk.editorial, facts } });
  const socialLinks = props.links.filter((link) => socials.some((name) => (link.label || link.kind).toLowerCase() === name.toLowerCase()));
  const platformLinks = props.links.filter((link) => !socialLinks.includes(link));
  return <div className="space-y-5">
    <Button variant="primary" fullWidth loading={saving} onClick={props.onSave}>Enregistrer les modifications</Button>
    <Section title="URL et couleur d’accent"><Field id="slug" label="Slug" value={epk.slug} onChange={(slug) => onChange({ ...epk, slug })} /><p className="-mt-3 text-xs text-[var(--fz-text-muted)]">faderzero.com/{epk.slug}</p><fieldset><legend className="fz-field-label">Couleur d’accent</legend><div className="mt-2 grid grid-cols-4 gap-2">{accentSwatches.map(([value, label, className]) => <button key={value} type="button" aria-label={label} aria-pressed={(epk.accentColor ?? '#ff3a63') === value} onClick={() => onChange({ ...epk, accentColor: value })} className={`h-11 w-11 rounded-full border-2 ${className} ${(epk.accentColor ?? '#ff3a63') === value ? 'border-white ring-2 ring-white/35' : 'border-transparent'}`} />)}</div></fieldset></Section>
    <Section title="Structure des sections"><div className="space-y-2">{(epk.sectionOrder ?? DEFAULT_EPK_SECTION_ORDER).map((section, index) => { const visible = !(epk.hiddenSections ?? []).includes(section); return <div key={section} className="flex items-center gap-2 rounded-xl border border-white/10 p-2"><span className="w-6 text-center text-xs text-white/45">{index + 1}</span><strong className="min-w-0 flex-1 text-sm">{labels[section]}</strong><button type="button" aria-label={visible ? `Masquer ${labels[section]}` : `Afficher ${labels[section]}`} disabled={section === 'banniere'} onClick={() => updateSections(epk.sectionOrder ?? DEFAULT_EPK_SECTION_ORDER, visible ? [...(epk.hiddenSections ?? []), section] : (epk.hiddenSections ?? []).filter((value) => value !== section))} className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/5 disabled:opacity-30"><FzIcon name={visible ? 'show-password' : 'hide-password'} usageId={`epk.structure.${section}.visibility`} /></button><Button variant="ghost" size="sm" disabled={index <= 1} onClick={() => move(index, -1)}>↑</Button><Button variant="ghost" size="sm" disabled={section === 'banniere' || index === (epk.sectionOrder ?? DEFAULT_EPK_SECTION_ORDER).length - 1} onClick={() => move(index, 1)}>↓</Button></div>; })}</div><Button variant="secondary" fullWidth onClick={() => updateSections([...DEFAULT_EPK_SECTION_ORDER], [])}>Réinitialiser l’ordre</Button></Section>
    <Section title="Bannière"><Field id="name" label="Nom du groupe" value={epk.displayName} onChange={(displayName) => onChange({ ...epk, displayName })} /><Field id="style" label="Style musical" value={epk.genres.join(' · ')} onChange={(value) => onChange({ ...epk, genres: value.split('·').map((item) => item.trim()).filter(Boolean) })} /><Field id="tagline" label="Phrase d’accroche" value={epk.tagline ?? ''} onChange={(tagline) => onChange({ ...epk, tagline })} /><FileField id="hero" label="Image de bannière" accept="image/jpeg,image/png,image/webp" disabled={saving} onPick={props.onUploadHero} hint="JPEG, PNG ou WebP, 10 Mo maximum. Format paysage 2400 × 1350 px recommandé." /></Section>
    <Section title="Biographie"><Field id="bio-title" label="Titre" value={epk.editorial.bioTitle} onChange={(bioTitle) => onChange({ ...epk, editorial: { ...epk.editorial, bioTitle } })} /><div><FieldLabel htmlFor="epk-bio-text">Texte de biographie</FieldLabel><TextArea id="epk-bio-text" rows={7} value={epk.fullBio ?? ''} onChange={(event) => onChange({ ...epk, fullBio: event.target.value })} /></div><Collection title="En bref">{epk.editorial.facts.map((fact, index) => <Card key={fact.id} onRemove={() => updateFacts(epk.editorial.facts.filter((_, itemIndex) => itemIndex !== index))} disabled={saving}><Field id={`fact-title-${fact.id}`} label="Titre" value={fact.title} onChange={(title) => updateFacts(epk.editorial.facts.map((item, itemIndex) => itemIndex === index ? { ...item, title } : item))} /><Field id={`fact-value-${fact.id}`} label="Valeur" value={fact.value} onChange={(value) => updateFacts(epk.editorial.facts.map((item, itemIndex) => itemIndex === index ? { ...item, value } : item))} /><div><FieldLabel htmlFor={`epk-fact-icon-${fact.id}`}>Icône</FieldLabel><SelectField id={`epk-fact-icon-${fact.id}`} value={fact.icon} onChange={(event) => updateFacts(epk.editorial.facts.map((item, itemIndex) => itemIndex === index ? { ...item, icon: event.target.value as typeof item.icon } : item))}><option value="location">Localisation</option><option value="music">Guitare</option><option value="users">Formation</option><option value="calendar">Éclair</option></SelectField></div></Card>)}<Button variant="secondary" fullWidth onClick={() => updateFacts([...epk.editorial.facts, { id: `fact-${Date.now()}`, title: '', value: '', icon: 'location' }])}>Ajouter un élément</Button></Collection></Section>
    <Section title="Musique"><Field id="music-title" label="Titre" value={epk.editorial.musicTitle} onChange={(musicTitle) => onChange({ ...epk, editorial: { ...epk.editorial, musicTitle } })} /><Collection title="Pistes audio">{props.tracks.map((track) => <Card key={track.id} onRemove={() => props.onRemoveTrack(track)} disabled={saving}><p className="font-semibold">{track.title}</p></Card>)}<div><FieldLabel htmlFor="epk-track">Audio du groupe</FieldLabel><SelectField id="epk-track" value={trackId} onChange={(event) => setTrackId(event.target.value)}><option value="">Choisir un audio…</option>{props.availableTracks.filter((track) => track.isSynced && !props.tracks.some((item) => item.songAssetId === track.id)).map((track) => <option key={track.id} value={track.id}>{track.songTitle || track.filename}</option>)}</SelectField></div><Button variant="secondary" fullWidth disabled={!trackId || saving} onClick={() => { props.onAddTrack(trackId); setTrackId(''); }}>Ajouter une piste</Button></Collection><Links title="Plateformes de streaming" names={platforms} name={platform} setName={setPlatform} url={platformUrl} setUrl={setPlatformUrl} items={platformLinks} onAdd={props.onAddLink} onRemove={props.onRemoveLink} limit={4} saving={saving} /></Section>
    <Section title="Médias"><Collection title="Vidéos YouTube" count={`${props.videos.length}/2`}>{props.videos.map((video) => <Card key={video.id} onRemove={() => props.onRemoveVideo(video)} disabled={saving}><p className="font-semibold">{video.title || `YouTube · ${video.providerVideoId}`}</p></Card>)}<Field id="video-title" label="Titre (optionnel)" value={videoTitle} onChange={setVideoTitle} /><Field id="video-url" label="URL YouTube" type="url" value={videoUrl} onChange={setVideoUrl} /><Button variant="secondary" fullWidth disabled={!videoUrl || props.videos.length >= 2 || saving} onClick={() => { props.onAddVideo(videoUrl, videoTitle, 'MUSIC_VIDEO'); setVideoUrl(''); setVideoTitle(''); }}>Ajouter une vidéo</Button></Collection><Collection title="Photos" count={`${props.photos.length}/10`}>{props.photos.map((photo) => <Card key={photo.id} onRemove={() => props.onRemovePhoto(photo)} disabled={saving}><p className="text-sm text-white/65">Photo importée</p></Card>)}<FileField id="photo" label="Ajouter une photo" accept="image/jpeg,image/png,image/webp" disabled={saving || props.photos.length >= 10} onPick={props.onUploadPhoto} /></Collection></Section>
    <Section title="Espace Pro"><Field id="pro-title" label="Titre" value={epk.editorial.proTitle} onChange={(proTitle) => onChange({ ...epk, editorial: { ...epk.editorial, proTitle } })} /><div><FieldLabel htmlFor="epk-pro-description">Description</FieldLabel><TextArea id="epk-pro-description" rows={3} value={epk.editorial.proDescription} onChange={(event) => onChange({ ...epk, editorial: { ...epk.editorial, proDescription: event.target.value } })} /></div><Collection title="Fichiers professionnels">{props.documents.map((document) => <Card key={document.id} onRemove={() => props.onRemoveDocument(document)} disabled={saving}><p className="font-semibold">{document.title}</p><p className="text-xs text-white/55">{document.documentType}</p></Card>)}<Field id="document-title" label="Nom" value={documentTitle} onChange={setDocumentTitle} /><div><FieldLabel htmlFor="epk-document-type">Type</FieldLabel><SelectField id="epk-document-type" value={documentType} onChange={(event) => setDocumentType(event.target.value as EpkDocumentType)}>{['TECH_RIDER', 'STAGE_PLOT', 'HOSPITALITY_RIDER', 'PRESS_KIT', 'LOGO', 'OTHER'].map((type) => <option key={type} value={type}>{type}</option>)}</SelectField></div><FileField id="document" label="Fichier PDF" accept="application/pdf" disabled={saving || !documentTitle.trim()} onPick={(file) => props.onUploadDocument(file, documentTitle, documentType)} hint="Indiquez le nom avant de sélectionner le fichier." /></Collection></Section>
    <Section title="Contact"><Field id="contact-title" label="Titre" value={epk.editorial.contactTitle} onChange={(contactTitle) => onChange({ ...epk, editorial: { ...epk.editorial, contactTitle } })} /><Collection title="Contacts">{props.contacts.map((contact) => <Card key={contact.id} onRemove={() => props.onRemoveContact(contact)} disabled={saving}><p className="font-semibold">{contact.name}</p><p className="text-sm text-white/65">{contact.role} · {contact.email || contact.phone || contact.whatsapp}</p></Card>)}<Field id="contact-name" label="Nom" value={contactName} onChange={setContactName} /><div><FieldLabel htmlFor="epk-contact-role">Rôle</FieldLabel><SelectField id="epk-contact-role" value={contactRole} onChange={(event) => setContactRole(event.target.value as EpkContactRole)}>{['BOOKING', 'PRESS', 'MANAGEMENT', 'TECH', 'BAND', 'PRODUCTION', 'OTHER'].map((role) => <option key={role} value={role}>{role}</option>)}</SelectField></div><div><FieldLabel htmlFor="epk-contact-type">Type</FieldLabel><SelectField id="epk-contact-type" value={contactType} onChange={(event) => setContactType(event.target.value as 'email' | 'phone')}><option value="email">E-mail</option><option value="phone">Téléphone</option></SelectField></div><Field id="contact-value" label="Valeur" type={contactType === 'email' ? 'email' : 'tel'} value={contactValue} onChange={setContactValue} /><Button variant="secondary" fullWidth disabled={!contactName || !contactValue || saving} onClick={() => { props.onAddContact(contactName, contactRole, contactValue, contactType); setContactName(''); setContactValue(''); }}>Ajouter un contact</Button></Collection><Links title="Réseaux sociaux" names={socials} name={social} setName={setSocial} url={socialUrl} setUrl={setSocialUrl} items={socialLinks} onAdd={props.onAddLink} onRemove={props.onRemoveLink} saving={saving} /></Section>
  </div>;
}

function Field({ id, label, value, onChange, type = 'text' }: { id: string; label: string; value: string; onChange: (value: string) => void; type?: 'text' | 'url' | 'email' | 'tel' }) { return <div><FieldLabel htmlFor={`epk-${id}`}>{label}</FieldLabel><TextField id={`epk-${id}`} type={type} value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
function FileField({ id, label, accept, disabled, onPick, hint }: { id: string; label: string; accept: string; disabled: boolean; onPick: (file: File) => void; hint?: string }) { return <div><FieldLabel htmlFor={`epk-${id}`}>{label}</FieldLabel><input id={`epk-${id}`} type="file" accept={accept} disabled={disabled} className="block min-h-11 w-full text-sm text-white" onChange={(event) => { const file = event.target.files?.[0]; if (file) onPick(file); event.currentTarget.value = ''; }} />{hint ? <p className="mt-1 text-xs text-[var(--fz-text-muted)]">{hint}</p> : null}</div>; }
function Collection({ title, count, children }: { title: string; count?: string; children: ReactNode }) { return <div className="space-y-3"><div className="flex items-center justify-between"><p className="fz-field-label">{title}</p>{count ? <span className="text-xs text-[var(--fz-text-muted)]">{count}</span> : null}</div>{children}</div>; }
function Card({ children, onRemove, disabled }: { children: ReactNode; onRemove: () => void; disabled: boolean }) { return <div className="space-y-3 rounded-xl border border-white/10 p-3">{children}<Button variant="danger" size="sm" fullWidth loading={disabled} onClick={onRemove}>Supprimer</Button></div>; }
function Links({ title, names, name, setName, url, setUrl, items, onAdd, onRemove, limit, saving }: { title: string; names: string[]; name: string; setName: (value: string) => void; url: string; setUrl: (value: string) => void; items: EpkLink[]; onAdd: (name: string, url: string) => void; onRemove: (item: EpkLink) => void; limit?: number; saving: boolean }) { const count = limit ? `${items.length}/${limit}` : undefined; return <Collection title={title} {...(count ? { count } : {})}>{items.map((item) => <Card key={item.id} onRemove={() => onRemove(item)} disabled={saving}><p className="font-semibold">{item.label || item.kind}</p><p className="truncate text-sm text-white/65">{item.url}</p></Card>)}<div><FieldLabel htmlFor={`${title}-name`}>Réseau</FieldLabel><SelectField id={`${title}-name`} value={name} onChange={(event) => setName(event.target.value)}>{names.map((option) => <option key={option} value={option}>{option}</option>)}</SelectField></div><Field id={`${title}-url`} label="URL" type="url" value={url} onChange={setUrl} /><Button variant="secondary" fullWidth disabled={!url || saving || (limit !== undefined && items.length >= limit)} onClick={() => { onAdd(name, url); setUrl(''); }}>Ajouter</Button></Collection>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <details className="rounded-2xl border border-white/10 bg-white/5 p-4" open><summary className="min-h-11 cursor-pointer list-none py-2 text-base font-black text-white">{title}</summary><div className="space-y-4 pt-3">{children}</div></details>; }
