import type { CSSProperties } from 'react';
import { epkOnAccentColor, isEpkSectionVisible, normalizedSectionOrder, type EpkPublicModel, type EpkSectionId } from './epkPresentation';
import './epkPublicView.css';

type Props = { model: EpkPublicModel; editing?: boolean; onEditSection?: (section: EpkSectionId) => void };
const titles: Record<EpkSectionId, string> = { banniere: 'Bannière', bio: 'Biographie', musique: 'Musique', medias: 'Médias', espacePro: 'Espace pro', contact: 'Contact' };
const icon: Record<string, string> = { location: '⌖', users: '◉', calendar: '◷', music: '♫' };

export function EpkPublicView({ model, editing = false, onEditSection }: Props) {
  const accent = /^#[0-9a-f]{6}$/i.test(model.accentColor) ? model.accentColor : '#ff3a63';
  const style = { '--epk-accent': accent, '--epk-on-accent': epkOnAccentColor(accent) } as CSSProperties;
  return <article className="epk-demo" style={style}><main>{normalizedSectionOrder(model.sectionOrder).map((section) => <Section key={section} section={section} model={model} visible={isEpkSectionVisible(model, section)} editing={editing} {...(onEditSection ? { onEditSection } : {})} />)}</main><footer>Propulsé par <strong>FaderZero</strong></footer></article>;
}

function Section({ section, model, visible, editing, onEditSection }: { section: EpkSectionId; model: EpkPublicModel; visible: boolean; editing: boolean; onEditSection?: (section: EpkSectionId) => void }) {
  if (!visible) return editing ? <section className="epk-empty"><span>{titles[section]} est masquée</span><button type="button" onClick={() => onEditSection?.(section)}>Configurer</button></section> : null;
  if (section === 'banniere') return <section id="banniere" className="epk-hero" style={model.heroUrl ? { backgroundImage: `url(${model.heroUrl})` } : undefined}><div className="epk-hero-shade" /><div className="epk-hero-content"><span className="epk-chip">{model.genres.join(' · ') || 'Electronic press kit'}</span><h1>{model.name}</h1><p>{model.tagline || model.genres.join(' · ')}</p><div className="epk-actions"><a href="#musique">▶ Écouter</a><a href="#espace-pro">▣ Espace Pro</a></div></div></section>;
  if (section === 'bio') return <section id="bio" className="epk-section epk-bio"><div><p className="epk-kicker">À propos</p><h2>{model.editorial.bioTitle}</h2><p className="epk-prose">{model.fullBio || model.shortBio}</p></div><aside><h3>En bref</h3>{model.editorial.facts.map((fact) => <div className="epk-fact" key={fact.id}><span>{icon[fact.icon]}</span><p><small>{fact.title}</small>{fact.value}</p></div>)}</aside></section>;
  if (section === 'musique') return <section id="musique" className="epk-section epk-music"><header><p className="epk-kicker">Discographie</p><h2>{model.editorial.musicTitle}</h2></header><div className="epk-music-grid"><div className="epk-player"><div className="epk-now"><span>♫</span><p><small>Lecture</small>{model.tracks[0]?.title || 'Aucune piste'}</p></div>{model.tracks.map((track, index) => <button type="button" className="epk-track" key={track.id} data-track={track.id}><i>{index === 0 ? '♫' : '▶'}</i><strong>{track.title}</strong><small>{String(index + 1).padStart(2, '0')}</small></button>)}</div><div className="epk-platforms">{model.links.filter((link) => !/instagram|facebook|tiktok/i.test(link.label)).map((link) => <a href={link.url} target="_blank" rel="noreferrer" key={link.url}><span>◉</span><p><strong>{link.label}</strong><small>Écouter sur la plateforme</small></p>↗</a>)}</div></div></section>;
  if (section === 'medias') return <section id="medias" className="epk-section epk-media"><header><p className="epk-kicker">Médias</p><h2>Vidéos &amp; Photos</h2></header>{model.videos.length ? <div className="epk-videos">{model.videos.map((video) => <a key={video.id} href={video.provider === 'VIMEO' ? `https://vimeo.com/${video.providerVideoId}` : `https://youtube.com/watch?v=${video.providerVideoId}`} target="_blank" rel="noreferrer">▶<strong>{video.title || 'Voir la vidéo'}</strong></a>)}</div> : null}<div className="epk-photos">{model.photos.map((photo) => <figure key={photo.id}><img src={photo.previewUrl} alt={photo.caption || `${model.name} — photo presse`} />{photo.credit ? <figcaption>{photo.credit}</figcaption> : null}</figure>)}</div></section>;
  if (section === 'espacePro') return <section id="espace-pro" className="epk-section epk-pro"><header><p className="epk-kicker">Professionnels</p><h2>{model.editorial.proTitle}</h2><p>{model.editorial.proDescription}</p></header><div>{model.documents.map((document) => <button key={document.id} type="button" data-document={document.assetId}><span>▧</span><small>{document.type.replaceAll('_', ' ')}</small><strong>{document.title}</strong><em>Ouvrir ↗</em></button>)}</div></section>;
  return <section id="contact" className="epk-section epk-contact"><header><p className="epk-kicker">Contact</p><h2>{model.editorial.contactTitle}</h2></header><div className="epk-contact-list">{model.contacts.map((contact) => <article key={`${contact.name}-${contact.role}`}><p><small>{contact.role}</small><strong>{contact.name}</strong>{contact.email ? <a href={`mailto:${contact.email}`}>{contact.email}</a> : contact.phone ? <a href={`tel:${contact.phone}`}>{contact.phone}</a> : null}</p><span>✉</span></article>)}</div><div className="epk-socials">{model.links.filter((link) => /instagram|facebook|tiktok/i.test(link.label)).map((link) => <a key={link.url} href={link.url} target="_blank" rel="noreferrer" aria-label={link.label}>◉</a>)}</div></section>;
}
