import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'; import { tmpdir } from 'node:os'; import { join, resolve } from 'node:path'; import { describe, expect, it } from 'vitest'; import { InventoryRepository, revision } from '../inventoryRepository';
const fixture=()=>({schemaVersion:1,unknownRoot:true,icons:[{occurrenceId:'a',page:'p',location:'l',current:'c',duplicate:'d',unknown:true,proposal:{lucideIcon:'Circle',reason:'r'},decision:{status:'review',notes:'n'}},{occurrenceId:'b',page:'q'}]});
async function temp(){const dir=await mkdtemp(join(tmpdir(),'catalog-')),file=join(dir,'inventory.json');if(resolve(file)===resolve(process.cwd(),'docs/icon-audit/icon-inventory.json'))throw new Error('real inventory guard');await writeFile(file,JSON.stringify(fixture()));return{dir,file,cleanup:()=>rm(dir,{recursive:true,force:true})};}
describe('InventoryRepository',()=>{it('reads valid content and stable byte revisions',async()=>{const t=await temp();try{const r=new InventoryRepository(t.file),a=await r.read(),b=await r.read();expect(a.inventory.icons).toHaveLength(2);expect(a.revision).toMatch(/^sha256:/);expect(a.revision).toBe(b.revision);expect(revision('a')).not.toBe(revision('a\n'));}finally{await t.cleanup();}});it('writes atomically preserving unknown data',async()=>{const t=await temp();try{const r=new InventoryRepository(t.file),before=await r.read(),next=structuredClone(before.inventory);(next.icons[0].proposal as any).faderzeroName='More';const saved=await r.save(next,before.revision),after=await r.read();expect(saved.revision).not.toBe(before.revision);expect((after.inventory.icons[0] as any).unknown).toBe(true);expect((after.inventory.icons[1] as any).occurrenceId).toBe('b');expect((await readFile(t.file,'utf8')).endsWith('\n')).toBe(true);}finally{await t.cleanup();}});it('rejects stale revisions without changing original',async()=>{const t=await temp();try{const r=new InventoryRepository(t.file),a=await r.read();await writeFile(t.file,JSON.stringify({...a.inventory,changed:true}));await expect(r.save(a.inventory,a.revision)).rejects.toMatchObject({code:'REVISION_CONFLICT'});}finally{await t.cleanup();}});it('rejects invalid inventory',async()=>{const t=await temp();try{await writeFile(t.file,'{}');await expect(new InventoryRepository(t.file).read()).rejects.toThrow();}finally{await t.cleanup();}});});
describe('repository failures and preservation',()=>{
 it.each(['{','[]'])('rejects malformed or incompatible JSON %s',async(content)=>{const t=await temp();try{await writeFile(t.file,content);await expect(new InventoryRepository(t.file).read()).rejects.toThrow();}finally{await t.cleanup();}});
 it('reports absent files',async()=>{const t=await temp();try{await rm(t.file);await expect(new InventoryRepository(t.file).read()).rejects.toThrow();}finally{await t.cleanup();}});
 it('keeps automatic fields and supports partial proposal/decision changes',async()=>{const t=await temp();try{const r=new InventoryRepository(t.file),a=await r.read(),n=structuredClone(a.inventory),one:any=n.icons[0];one.proposal={...one.proposal,faderZeroName:'Name'};one.decision={...one.decision,notes:''};await r.save(n,a.revision);const after:any=await r.read();expect(after.inventory.icons[0]).toMatchObject({occurrenceId:'a',page:'p',location:'l',current:'c',duplicate:'d',unknown:true,proposal:{lucideIcon:'Circle',reason:'r',faderZeroName:'Name'},decision:{status:'review',notes:''}});}finally{await t.cleanup();}});
});
