import {
  ArrowLeft, ArrowRight, AudioLines, BriefcaseBusiness, Building2, Cable, CalendarDays, CalendarPlus, Check, ChevronDown, ClipboardList, Clock, CloudDownload, Copy, Disc3, Drum, Ellipsis, Eye, EyeOff, ExternalLink, FileArchive, FileDown, FileMusic, FileText, Filter, Flag, Flame, Folder, Globe2, Guitar,
  Heart, House, Images, Languages, Library, ListChecks, ListMusic, Maximize, Metronome, Mic, MicVocal, Monitor, Music, Pause, Pencil, Play,
  Mail, MapPin, Music2, Phone, Plus, Radio, Settings, Sparkles, Speaker, Square, Star, Trash2, Upload, UserRound, Users, Wrench, X, Zap,
  createLucideIcon, type LucideIcon,
} from 'lucide-react';
const PhonePlus = createLucideIcon('PhonePlus', [
  ['path', { d: 'M13.8 18.4a1 1 0 0 1-1.1.2 17.5 17.5 0 0 1-7.3-7.3 1 1 0 0 1 .2-1.1l2-2a1 1 0 0 0 .2-1l-1-3.1a1 1 0 0 0-1-.7H3.1A1.1 1.1 0 0 0 2 4.5 17.5 17.5 0 0 0 19.5 22a1.1 1.1 0 0 0 1.1-1.1v-2.7a1 1 0 0 0-.7-1l-3.1-1a1 1 0 0 0-1 .2z', key: 'phone' }],
  ['path', { d: 'M19 2v6', key: 'plus-v' }],
  ['path', { d: 'M16 5h6', key: 'plus-h' }],
]);
// Fallback registry committed for local/offline builds. The Cloudflare preparation
// step may regenerate this module from the last approved publication.
export const publishedIconComponents: Record<string, LucideIcon> = {
  add: Plus,
  back: ArrowLeft,
  calendar: CalendarDays,
  check: Check,
  'chevron-down': ChevronDown,
  close: X,
  delete: Trash2,
  download: CloudDownload,
  edit: Pencil,
  folder: Folder,
  fullscreen: Maximize,
  home: House,
  menu: Ellipsis,
  metronome: Metronome,
  pause: Pause,
  play: Play,
  prompter: Monitor,
  record: Mic,
  setlist: ListMusic,
  settings: Settings,
  songs: Library,
  stop: Square,
  upload: Upload,
  'show-password': Eye,
  'hide-password': EyeOff,
  'export-pdf': FileDown,
  phone: Phone,
  'phone-add': PhonePlus,
  'calendar-add': CalendarPlus,
  filter: Filter,
  email: Mail,
  'external-link': ExternalLink,
  copy: Copy,
  next: ArrowRight,
  location: MapPin,
  users: Users,
  music: Music2,
  star: Star,
  'clipboard-list': ClipboardList,
  'list-checks': ListChecks,
  wrench: Wrench,
  cable: Cable,
  'mic-vocal': MicVocal,
  speaker: Speaker,
  'audio-lines': AudioLines,
  images: Images,
  'briefcase-business': BriefcaseBusiness,
  'file-music': FileMusic,
  'file-archive': FileArchive,
  'file-text': FileText,
  'globe-2': Globe2,
  flag: Flag,
  'building-2': Building2,
  guitar: Guitar,
  drum: Drum,
  'music-note': Music,
  'user-round': UserRound,
  clock: Clock,
  heart: Heart,
  radio: Radio,
  'disc-3': Disc3,
  zap: Zap,
  flame: Flame,
  languages: Languages,
  sparkles: Sparkles,
};

export const publishedIconUsageOverrides: Record<string, LucideIcon> = {};
