import { FzIcon } from '@/ui/icons';
import { getAppUrl } from '@/utils/domainRouting';
import { SmartphoneFrame } from './SmartphoneFrame';
import { PhoneMetronomeView, PhonePrompterView } from './RealAppScreenshots';

const workflow = [
  ['01 / CAPTURE', 'Enregistre l’idée.', 'Un mémo vocal au milieu de la répétition. Il reste attaché au bon morceau, avec les notes, le BPM, la tonalité et les paroles.', 'REC'],
  ['02 / PRÉPARE', 'Construis le set.', 'Réordonne les titres, note les transitions, garde les pistes utiles à portée de main et prépare la soirée sans multiplier les fichiers.', '≡'],
  ['03 / JOUE', 'Passe en mode scène.', 'Prompteur plein écran, métronome, Tap Tempo et contenu disponible hors connexion. Sur scène, l’outil s’efface derrière le concert.', '▶'],
] as const;
const features = [
  ['Répertoire', 'Morceaux & paroles', 'Statut, tonalité, BPM, durée, notes et paroles restent regroupés autour du morceau.'],
  ['Audio', 'Pistes & mémos', 'Importe, écoute et télécharge les pistes utiles. Capture aussi une idée vocale sans casser le rythme.'],
  ['Live', 'Prompteur', 'Un affichage dédié à la scène pour les paroles et les informations essentielles du morceau.'],
  ['Préparation', 'Setlists', 'Crée, réordonne et annote tes sets. Exporte-les en PDF quand il faut les partager.'],
  ['Timing', 'Métronome', 'Tempo, Tap Tempo et accès direct depuis le workflow de répétition ou de scène.'],
  ['Équipe', 'Collaboration', 'Espaces partagés, rôles et invitations pour que tout le groupe travaille sur la même base.'],
  ['Agenda', 'Répètes & concerts', 'Planifie les événements du groupe sans séparer l’agenda du reste de la préparation musicale.'],
] as const;

function Label({ children }: { children: string }) { return <p className="mb-5 font-mono text-[.7rem] uppercase tracking-[.14em] text-white/40">{children}</p>; }

export function LandingNarrative() {
  const appUrl = getAppUrl('/?view=app');
  return <>
    <section className="border-b border-white/10 bg-[#0a0b0e]"><div className="mx-auto grid max-w-7xl grid-cols-2 px-4 sm:grid-cols-4 sm:px-6 lg:px-8">{['Pensé mobile|PWA mobile-first', 'Joue sans réseau|Audio & données en cache', 'Conçu pour un groupe|Espaces, rôles, invitations', 'Du local au cloud|Sync quand ça revient'].map((value) => { const [title, detail] = value.split('|'); return <div key={title} className="border-r border-white/10 px-4 py-7 last:border-r-0 sm:px-7"><b className="block text-sm text-white">{title}</b><span className="mt-1 block text-[.6rem] font-mono uppercase tracking-[.1em] text-white/40">{detail}</span></div>; })}</div></section>

    <section id="workflow" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><Label>01 — Le workflow</Label><h2 className="max-w-4xl text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl">Une app qui suit le groupe. Pas l’inverse.</h2><p className="mt-5 max-w-2xl text-base leading-relaxed text-white/60 sm:text-lg">FaderZero rassemble ce qui finit d’habitude dans six apps, trois conversations et un dossier Drive. Le morceau reste le point central, de l’idée brute jusqu’à la scène.</p><div className="mt-14 grid border-y border-white/10 md:grid-cols-3">{workflow.map(([number, title, copy, glyph]) => <article key={number} className="relative min-h-80 overflow-hidden border-b border-white/10 p-7 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><span className="font-mono text-xs text-white/40">{number}</span><h3 className="mt-20 text-3xl font-black tracking-[-.04em]">{title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-white/60">{copy}</p><span className="absolute -bottom-8 -right-4 text-8xl font-black text-white/[.06]">{glyph}</span></article>)}</div></section>

    <section id="stage" className="overflow-hidden border-y border-white/10 bg-[radial-gradient(circle_at_72%_45%,rgba(255,58,99,.14),transparent_38%),#07080b] py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-[.82fr_1.18fr] lg:px-8"><div><Label>02 — Live mode</Label><h2 className="text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-7xl">Sur scène,<br />zéro friction.</h2><p className="mt-6 max-w-lg text-base leading-relaxed text-white/65 sm:text-lg">Les outils utiles au concert sont lisibles, directs et accessibles en quelques secondes. Pas de tableau de bord à administrer pendant que le public attend.</p><ol className="mt-8 divide-y divide-white/10 border-y border-white/10">{['Prompteur plein écran avec informations du morceau', 'Métronome et Tap Tempo directement dans l’app', 'Setlists annotées et réordonnables', 'Pistes téléchargées lisibles sans réseau'].map((item, index) => <li key={item} className="flex gap-4 py-4 text-sm font-bold text-white/80"><span className="font-mono text-[#ff3a63]">0{index + 1}</span>{item}</li>)}</ol></div><div className="relative mx-auto flex h-[31rem] w-full max-w-xl items-center justify-center"><div className="absolute left-8 w-[13.5rem] -rotate-6 opacity-90"><SmartphoneFrame notchLabel="Prompteur live"><PhonePrompterView /></SmartphoneFrame></div><div className="absolute right-6 top-20 w-[13.5rem] rotate-6 opacity-85"><SmartphoneFrame notchLabel="128 BPM"><PhoneMetronomeView /></SmartphoneFrame></div></div></div></section>

    <section id="offline" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><Label>03 — Offline first</Label><h2 className="text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl">Quand le réseau lâche,<br />le groupe continue.</h2><div className="mt-12 grid gap-8 lg:grid-cols-2"><div className="rounded-[1.8rem] border border-white/10 bg-[#111319] p-5 sm:p-8"><div className="flex items-center justify-between border-b border-white/10 pb-5"><b>Prêt pour la scène</b><span className="rounded-full bg-amber-400/15 px-3 py-1 text-[.65rem] font-black uppercase tracking-[.12em] text-amber-300">Hors ligne</span></div>{[['Setlist — Live Nantes', '7 morceaux disponibles', 'LOCAL'], ['Pistes audio', '5 fichiers téléchargés', 'OK'], ['Paroles & notes', 'Dernière synchro 18:42', 'OK'], ['Modifications', '2 changements en attente', 'QUEUE']].map(([title, detail, state]) => <div key={title} className="flex items-center gap-3 border-b border-white/5 py-4 last:border-0"><FzIcon name="check" usageId={`landing.offline.${state}`} size="sm" className="text-emerald-400" /><div className="flex-1"><b className="block text-sm">{title}</b><span className="text-xs text-white/45">{detail}</span></div><span className="font-mono text-[.65rem] text-emerald-300">{state}</span></div>)}</div><div className="flex flex-col justify-center"><h3 className="text-3xl font-black tracking-[-.04em]">La connexion devient une option, pas une condition.</h3><p className="mt-5 text-base leading-relaxed text-white/60">Répète dans une cave, joue dans une salle saturée, prépare un set dans le train. FaderZero garde le nécessaire localement et synchronise les changements dès que possible.</p><p className="mt-6 font-mono text-xs uppercase tracking-[.08em] text-[#ff7a96]">Données locales · File de synchronisation · Audio en cache · Transfert QR</p></div></div></section>

    <section id="features" className="border-y border-white/10 bg-[#0a0b0e] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><Label>04 — Tout au même endroit</Label><h2 className="text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl">Moins d’outils.<br />Plus de musique.</h2><p className="mt-5 max-w-2xl text-base leading-relaxed text-white/60">Chaque fonction a une raison d’être dans le flux réel d’un groupe. Rien n’est là pour remplir une fiche produit.</p><div className="mt-12 grid gap-px overflow-hidden rounded-[1.8rem] border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{features.map(([tag, title, copy]) => <article key={title} className="min-h-56 bg-[#101217] p-6"><span className="font-mono text-[.65rem] uppercase tracking-[.12em] text-white/35">{tag}</span><h3 className="mt-12 text-xl font-black tracking-[-.03em]">{title}</h3><p className="mt-3 text-sm leading-relaxed text-white/55">{copy}</p></article>)}</div></div></section>

    <section id="epk" className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-2 lg:px-8"><div><Label>05 — Côté pro</Label><h2 className="text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl">Et quand il faut se présenter, le groupe est déjà prêt.</h2><p className="mt-6 max-w-xl text-base leading-relaxed text-white/60">FaderZero permet aussi de publier un EPK public : un lien propre pour envoyer bio, musique, médias, informations professionnelles et contact.</p><a href={appUrl} className="mt-7 inline-flex min-h-12 items-center rounded-xl border border-white/15 px-5 text-sm font-black">Créer l’espace du groupe →</a></div><div className="rounded-[1.8rem] border border-white/15 bg-[#111319] p-3 shadow-2xl"><div className="flex gap-1.5 border-b border-white/10 p-2"><i className="h-2 w-2 rounded-full bg-rose-400" /><i className="h-2 w-2 rounded-full bg-amber-300" /><i className="h-2 w-2 rounded-full bg-emerald-400" /></div><div className="min-h-80 bg-[radial-gradient(circle_at_70%_20%,rgba(255,58,99,.32),transparent_38%),#171018] p-8 sm:p-12"><span className="font-mono text-[.65rem] uppercase tracking-[.16em] text-rose-200">Electronic press kit</span><h3 className="mt-12 text-5xl font-black leading-[.8] tracking-[-.08em] sm:text-7xl">NIGHT<br />DRIVE</h3><p className="mt-5 text-sm text-white/65">Rock · Nantes, FR · Booking 2026</p><div className="mt-8 flex flex-wrap gap-2 text-[.65rem] font-black"><span className="rounded bg-white px-3 py-2 text-black">ÉCOUTER</span><span className="rounded border border-white/30 px-3 py-2">FICHE TECHNIQUE</span><span className="rounded border border-white/30 px-3 py-2">CONTACT</span></div></div></div></section>
  </>;
}
