import { FzIcon } from '@/ui/icons';
import { getAppUrl } from '@/utils/domainRouting';
import type { Language } from '../i18n/landingContent';
import { LANDING_NARRATIVE_CONTENT } from '../i18n/landingNarrativeContent';
import { SmartphoneFrame } from './SmartphoneFrame';
import { PhoneMetronomeView, PhonePrompterView } from './RealAppScreenshots';

function Label({ children }: { children: string }) { return <p className="mb-5 font-mono text-[.7rem] uppercase tracking-[.14em] text-white/40">{children}</p>; }

export function LandingNarrative({ lang }: { lang: Language }) {
  const appUrl = getAppUrl('/?view=app');
  const copy = LANDING_NARRATIVE_CONTENT[lang];
  return <>
    <section className="border-b border-white/10 bg-[#0a0b0e]"><div className="mx-auto grid max-w-7xl grid-cols-2 px-4 sm:grid-cols-4 sm:px-6 lg:px-8">{copy.proof.map(([title, detail]) => <div key={title} className="border-r border-white/10 px-4 py-7 last:border-r-0 sm:px-7"><b className="block text-sm text-white">{title}</b><span className="mt-1 block font-mono text-[.6rem] uppercase tracking-[.1em] text-white/40">{detail}</span></div>)}</div></section>

    <section id="workflow" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><Label>{copy.workflow.label}</Label><h2 className="max-w-4xl text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl">{copy.workflow.title}</h2><p className="mt-5 max-w-2xl text-base leading-relaxed text-white/60 sm:text-lg">{copy.workflow.description}</p><div className="mt-14 grid border-y border-white/10 md:grid-cols-3">{copy.workflow.items.map(([number, title, description, glyph]) => <article key={number} className="relative min-h-80 overflow-hidden border-b border-white/10 p-7 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><span className="font-mono text-xs text-white/40">{number}</span><h3 className="mt-20 text-3xl font-black tracking-[-.04em]">{title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-white/60">{description}</p><span className="absolute -bottom-8 -right-4 text-8xl font-black text-white/[.06]">{glyph}</span></article>)}</div></section>

    <section id="stage" className="overflow-hidden border-y border-white/10 bg-[radial-gradient(circle_at_72%_45%,rgba(255,58,99,.14),transparent_38%),#07080b] py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-[.82fr_1.18fr] lg:px-8"><div><Label>{copy.stage.label}</Label><h2 className="text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-7xl">{copy.stage.title[0]}<br />{copy.stage.title[1]}</h2><p className="mt-6 max-w-lg text-base leading-relaxed text-white/65 sm:text-lg">{copy.stage.description}</p><ol className="mt-8 divide-y divide-white/10 border-y border-white/10">{copy.stage.points.map((item, index) => <li key={item} className="flex gap-4 py-4 text-sm font-bold text-white/80"><span className="font-mono text-[#ff3a63]">0{index + 1}</span>{item}</li>)}</ol></div><div className="relative mx-auto flex h-[31rem] w-full max-w-xl items-center justify-center"><div className="absolute left-8 w-[13.5rem] -rotate-6 opacity-90"><SmartphoneFrame notchLabel={copy.stage.prompterLabel}><PhonePrompterView /></SmartphoneFrame></div><div className="absolute right-6 top-20 w-[13.5rem] rotate-6 opacity-85"><SmartphoneFrame notchLabel="128 BPM"><PhoneMetronomeView /></SmartphoneFrame></div></div></div></section>

    <section id="offline" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><Label>{copy.offline.label}</Label><h2 className="text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl">{copy.offline.title[0]}<br />{copy.offline.title[1]}</h2><div className="mt-12 grid gap-8 lg:grid-cols-2"><div className="rounded-[1.8rem] border border-white/10 bg-[#111319] p-5 sm:p-8"><div className="flex items-center justify-between border-b border-white/10 pb-5"><b>{copy.offline.ready}</b><span className="rounded-full bg-amber-400/15 px-3 py-1 text-[.65rem] font-black uppercase tracking-[.12em] text-amber-300">{copy.offline.badge}</span></div>{copy.offline.status.map(([title, detail, state]) => <div key={title} className="flex items-center gap-3 border-b border-white/5 py-4 last:border-0"><FzIcon name="check" usageId={`landing.offline.${state}`} size="sm" className="text-emerald-400" /><div className="flex-1"><b className="block text-sm">{title}</b><span className="text-xs text-white/45">{detail}</span></div><span className="font-mono text-[.65rem] text-emerald-300">{state}</span></div>)}</div><div className="flex flex-col justify-center"><h3 className="text-3xl font-black tracking-[-.04em]">{copy.offline.heading}</h3><p className="mt-5 text-base leading-relaxed text-white/60">{copy.offline.description}</p><p className="mt-6 font-mono text-xs uppercase tracking-[.08em] text-[#ff7a96]">{copy.offline.technologies}</p></div></div></section>

    <section id="features" className="border-y border-white/10 bg-[#0a0b0e] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><Label>{copy.features.label}</Label><h2 className="text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl">{copy.features.title[0]}<br />{copy.features.title[1]}</h2><p className="mt-5 max-w-2xl text-base leading-relaxed text-white/60">{copy.features.description}</p><div className="mt-12 grid gap-px overflow-hidden rounded-[1.8rem] border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{copy.features.items.map(([tag, title, description]) => <article key={title} className="min-h-56 bg-[#101217] p-6"><span className="font-mono text-[.65rem] uppercase tracking-[.12em] text-white/35">{tag}</span><h3 className="mt-12 text-xl font-black tracking-[-.03em]">{title}</h3><p className="mt-3 text-sm leading-relaxed text-white/55">{description}</p></article>)}</div></div></section>

    <section id="epk" className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-2 lg:px-8"><div><Label>{copy.epk.label}</Label><h2 className="text-4xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl">{copy.epk.title}</h2><p className="mt-6 max-w-xl text-base leading-relaxed text-white/60">{copy.epk.description}</p><a href={appUrl} className="mt-7 inline-flex min-h-12 items-center rounded-xl border border-white/15 px-5 text-sm font-black">{copy.epk.cta}</a></div><div className="rounded-[1.8rem] border border-white/15 bg-[#111319] p-3 shadow-2xl"><div className="flex gap-1.5 border-b border-white/10 p-2"><i className="h-2 w-2 rounded-full bg-rose-400" /><i className="h-2 w-2 rounded-full bg-amber-300" /><i className="h-2 w-2 rounded-full bg-emerald-400" /></div><div className="min-h-80 bg-[radial-gradient(circle_at_70%_20%,rgba(255,58,99,.32),transparent_38%),#171018] p-8 sm:p-12"><span className="font-mono text-[.65rem] uppercase tracking-[.16em] text-rose-200">Electronic press kit</span><h3 className="mt-12 text-5xl font-black leading-[.8] tracking-[-.08em] sm:text-7xl">NIGHT<br />DRIVE</h3><p className="mt-5 text-sm text-white/65">{copy.epk.genre}</p><div className="mt-8 flex flex-wrap gap-2 text-[.65rem] font-black"><span className="rounded bg-white px-3 py-2 text-black">{copy.epk.listen}</span><span className="rounded border border-white/30 px-3 py-2">{copy.epk.technical}</span><span className="rounded border border-white/30 px-3 py-2">{copy.epk.contact}</span></div></div></div></section>
  </>;
}
